# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Afterglow
include current-theme.conf
# END_KITTY_THEME

shell_integration no-cursor
# cursor #cccccc
# cursor_text_color #111111

cursor_shape block
cursor_shape_unfocused hollow
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
cursor_blink_interval 0.7 linear

tab_bar_align 		    left
tab_bar_min_tabs            1
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          " {tab.active_exe} "

shell bash --rcfile /home/nam/.config/kitty/bashrc

background_opacity         0.8
dynamic_background_opacity yes
window_padding_width       6
